# Page settings

baseURL = "https://resume.beingadityak.com/"
languageCode = "en"
title = "Aditya Krishnakumar - Resume"
theme = "hugo-devresume-theme"

publishDir = "docs"

[params]

    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Aditya Krishnakumar"
        tagline = "DevOps Consultant"
        avatar = "aditya_krishnakumar.jpeg"

    [params.contact]
        enable = true
        location = "India"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:+919825024057"
        text = "(+91) 98250 24057"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:me@beingadityak.com"
        text = "me@beingadityak.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "//beingadityak.com"
        text = "beingadityak.com"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Python, Bash"
        [[params.skills.list.items]]
        details = "Terraform, Packer, Docker, Docker Compose"
        [[params.skills.list.items]]
        details = "Ansible, Kubernetes"
        [[params.skills.list.items]]
        details = "Datadog, AWS CloudWatch, Elastic Stack (EFK), Prometheus, Grafana, Loki"
        [[params.skills.list.items]]
        details = "Jenkins, Azure DevOps, Github Actions, GitOps, ArgoCD, Flux"
        [[params.skills.list.items]]
        details = "AWS, Google Cloud Platform (GCP)"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems, Site Reliability Engineering"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "B.Tech in Computer Engineering"
        university = "Dharmsinh Desai University, Nadiad, Gujarat"
        dates = "2014 - 2018"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "Hindi"
        level = "Native"
        [[params.languages.list]]
        name = "Gujarati"
        level = "Native"
        [[params.languages.list]]
        name = "Malayalam"
        level = "Limited"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Cycling"
        [[params.interests.list]]
        name = "Gymming"
        [[params.interests.list]]
        name = "Travelling"

    [params.summary]
        enable = true
        text = "A technically savvy professional having 5+ years of experience working with emerging technologies tied to DevOps, where for the major part he has spent in simplifying automation for Small & Medium Businesses (SMBs) as well as enterprise clients. He has worked for industries such as Management Consulting, Media & Broadcasting and Technology Services. In his role as a DevOps Engineer, he orchestrates the journey of software development from commit to production. He drives performance and reliability across multiple platforms, working closely with development and QA teams to understand requirements for build, test, deploy and release processes. His experience crosses shortening and automating testing and release cycles to get it done faster."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "DevOps Engineer"
        dates = "Aug 2021 - Apr 2023"
        company = "Boston Consulting Group (BCG)"
        details = "Worked as a DevOps Engineer as well as a Site Reliability Engineer for one of the SaaS analytics platform developed for customers of Retail industry."
        [[params.experience.list.items]]
        details = "Worked on DevOps & SRE activities for Retail Catalyst, an analytics SaaS-based platform for retail industry."
        [[params.experience.list.items]]
        details = "Worked with global product development & operations team out of Chicago (US), Warsaw (Poland) and Bengaluru (India)"
        [[params.experience.list.items]]
        details = "Implemented DevSecOps practices by integrating Veracode in the CI/CD process, using Orca Security for any alerts and vulnerabilities in the infrastructure as well as setting up patch management for machines in the infrastructure."
        [[params.experience.list.items]]
        details = "Worked on achieving the SOC 2 Type 1 compliance attestation of the platform as well as setting up the foundations for the SOC 2 Type 2 compliance attestation."
        [[params.experience.list.items]]
        details = "Developed automation in Terraform for the supporting Virtual Machines as well as the Kubernetes clusters."
        [[params.experience.list.items]]
        details = "Worked on setting up monitoring platform in Datadog for the SaaS platform."


        [[params.experience.list]]
        title = "DevOps Engineer"
        dates = "May 2019 - Aug 2021"
        company = "Intellimedia Networks"
        details = "Performed a lot of RnD as well as support work for my internal as well as external customers. I learned a lot more from this organization about team management, project management and execution as well as improved communication skills. I was also fortunate to work with LiveU, one of the largest news broadcasting product-based firm based in US."
        [[params.experience.list.items]]
        details = "Worked majorly on the DevOps activities in LiveU, one of the largest news broadcasting product-based firm."
        [[params.experience.list.items]]
        details = "Worked with R&D teams based out of Israel and Ahmedabad, India."
        [[params.experience.list.items]]
        details = "Led the development and delivered an internal server creation tool, which reduced the time for creating the server from ~30 minutes (which was also prone to errors) to ~10 minutes. The tool also allows to create servers in multiple regions as well as in multiple AWS accounts."
        [[params.experience.list.items]]
        details = "Handled the server management for one of the components of a successful product from LiveU. The applications were developed mostly in Node.js"
        [[params.experience.list.items]]
        details = "Handled provisioning and system administration tasks for the web and database servers for the organization's other projects in AWS."
        [[params.experience.list.items]]
        details = "Created, optimized and managed CI/CD pipelines for projects developed in JavaScript (both front-end and back-end) as well as PHP in Bitbucket Pipelines for the deployment to AWS as well as non-AWS (Vultr) instances."
        [[params.experience.list.items]]
        details = "Redesigned the infrastructure for a 3-tier web application in AWS. Streamlined the development, deployment as well as monitoring and logging experiences on AWS with Elastic Beanstalk, AWS CloudWatch logs and Bitbucket Pipelines"
        [[params.experience.list.items]]
        details = "Achieved my other AWS associate and Professional as well as other Clouds' certifications such as Terraform, Microsoft, Google Cloud etc. along with my day-to-day work."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "Dec 2017 - May 2019"
        company = "Crest Data Systems"
        details = "Worked majorly as an SRE for Splunk Cloud, a SaaS offering by Splunk."
        [[params.experience.list.items]]
        details = "Worked majorly on maintenance and support of Splunk Cloud infrastructure."
        [[params.experience.list.items]]
        details = "Worked with Operations (NOC) and SRE teams distributed across APAC, Americas & EMEA regions for the support and maintenance of Splunk Cloud platform."
        [[params.experience.list.items]]
        details = "Performed updates as well as creation of 5 operational runbooks for the documentation and maintenance of systems and processes for using Ansible, Puppet & Terraform."
        [[params.experience.list.items]]
        details = "Involved in a major maintenance task which required me to work with other CloudOps Engineers to migrate the backing of the EBS volumes to the newer specification released by the team."
        [[params.experience.list.items]]
        details = "Created a maintenance helper script which helped the team members to perform checks on the Splunk Cloud instances whenever there is a maintenance notification from AWS Support regarding instance degradation."
        [[params.experience.list.items]]
        details = "Created multiple one-off scripts which helped the team in performing their day-to-day operations work."
        [[params.experience.list.items]]
        details = "Worked as a lead engineer in the 6 months of 'Infrastructure Automation Migration', serving 100+ customers."
        [[params.experience.list.items]]
        details = "Performed on-call operations for any escalations during migration."
        [[params.experience.list.items]]
        details = "Achieved my AWS Certified Solutions Architect & Cloud Practitioner certification along with my day-to-day work."


    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Terraform for OpenDistro"
        tagline = "Terraform code for setting up OpenDistro nodes along with backup process using multiple AWS services such as EC2, ECS, ELB etc. as well as using KMS and SOPS for secrets management."

        [[params.projects.list]]
        title = "Terraform + CI/CD + Packer setup for a SaaS product"
        tagline = "Created automation in Terraform for setting up a 3-tier application written in Node.js in AWS cloud as well as setting up CI/CD pipelines and Packer image deployment templates using GitHub Actions for the code."

        [[params.projects.list]]
        title = "Automated deployment of Splunk"
        tagline = "Automation for deployment of Splunk for dev environments using Terraform, Packer and AWS Cloud with a centralized Jenkins pipeline"

        [[params.projects.list]]
        title = "Splunk Cloud Migration"
        tagline = "Worked as a part of a specialist team for migrating customer environments from legacy automation platform (Ansible + CloudFormation + Chef) to the next gen automation platform (Terraform + Puppet)"

    [params.certifications]
        enable = true

        [[params.certificate.list]]
        title = "HashiCorp Certified - Terraform Associate"
        date = "August 2020"
        company = "HashiCorp"

        [[params.certificate.list]]
        title = "Google Cloud Certified Associate Cloud Engineer"
        date = "July 2020"
        company = "Google Cloud"

        [[params.certificate.list]]
        title = "AWS Certified DevOps Engineer - Professional"
        date = "July 2020"
        company = "Amazon Web Services"

        [[params.certificate.list]]
        title = "AWS Certified DevOps Engineer - Professional"
        date = "July 2020"
        company = "Amazon Web Services"

        [[params.certificate.list]]
        title = "Microsoft Certified: Azure DevOps Engineer Expert"
        date = "May 2020"
        company = "Microsoft"

    [params.information]
        enable = true

        [[params.information.list]]
        title = "Interests"
        details = "Cycling, Gymming, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/beingadityak"
        title = "beingadityak"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/beingadityak"
        title = "beingadityak"